#!/bin/sh

# move to /usr/local/bin/log_parse

# change this according your environment
ip_syslog="10.10.0.99"
port_syslog="514"

clog1pid="/var/run/clog1.pid"
clog2pid="/var/run/clog2.pid"
tailpid="/var/run/tail.pid"

stop()
{
  if [ -e "${clog1pid}" ]; then
    echo "Killing " `cat ${clog1pid}`
    kill `cat ${clog1pid}`
    rm ${clog1pid}
  fi

  if [ -e "${clog2pid}" ]; then
    echo "Killing " `cat ${clog2pid}`
    kill `cat ${clog2pid}`
    rm ${clog2pid}
  fi

  if [ -e "${tailpid}" ]; then
    echo "Killing " `cat ${tailpid}`
    kill `cat ${tailpid}`
    rm ${tailpid}
  fi

}

start()
{
  stop
  /usr/local/sbin/clog -f /var/log/filter.log > /var/log/filter.log.txt &
  if [ $? != 0 ]; then
    echo "Fail exec clog"
    return 1
  fi
  echo $! > ${clog1pid}
  echo "Started process " `cat ${clog1pid}`


  /usr/local/sbin/clog -f /var/log/portalauth.log | grep logportalauth >> /var/log/portalauth.log.txt &
  if [ $? != 0 ]; then
    echo "Fail exec clog"
    return 1
  fi
  echo $! > ${clog2pid}
  echo "Started process " `cat ${clog1pid}`


  (/usr/bin/tail -f -n0 /var/log/filter.log.txt  & echo $! > ${tailpid}) | \
  /usr/local/bin/python3.6 /usr/local/bin/parse_filter_captive.py | \
  /usr/bin/logger -t captive_pfsense -h ${ip_syslog} -P ${port_syslog} -4 &
  if [ $? != 0 ]; then
    echo "Fail exec"
    return 1
  fi
  echo "Started process " `cat ${tailpid}`

  echo "Started"
}

restart()
{
  stop()
  start()
  echo "Restarted"
}

status()
{
  if [ -e "${tailpid}" ] && [ -e "${clog2pid}" ] && [ -e "${clog1pid}" ]; then
    echo "Is running OK"
    return 0
  else
    echo "Not running"
    return 1
  fi
}

usage()
{
  echo "Usage: $0 (start | stop | restart | status)"
  return 1
}

case $1 in
  start) start ;;
  stop) stop ; echo "Stopped";;
  restart) stop ; start ;;
  status) status ;;
  *) usage ;;
esac
